name: Deploy EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy para EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/busca

            git pull

            docker stop app-busca || true
            docker rm app-busca || true

            docker build -t busca:latest .

            docker run -d \
              --name app-busca \
              -p 5000:5000 \
              --restart unless-stopped \
              busca:latest